/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountCredentials
 */
export interface AccountCredentials {
    /**
     * 
     * @type {string}
     * @memberof AccountCredentials
     */
    emailaddress: string;
    /**
     * 
     * @type {string}
     * @memberof AccountCredentials
     */
    password: string;
}

/**
 * Check if a given object implements the AccountCredentials interface.
 */
export function instanceOfAccountCredentials(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "emailaddress" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AccountCredentialsFromJSON(json: any): AccountCredentials {
    return AccountCredentialsFromJSONTyped(json, false);
}

export function AccountCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCredentials {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailaddress': json['emailaddress'],
        'password': json['password'],
    };
}

export function AccountCredentialsToJSON(value?: AccountCredentials | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailaddress': value.emailaddress,
        'password': value.password,
    };
}

