/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDashboardResponseData
 */
export interface ApiDashboardResponseData {
    /**
     * 
     * @type {string}
     * @memberof ApiDashboardResponseData
     */
    token?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiDashboardResponseData
     */
    result?: object;
}

/**
 * Check if a given object implements the ApiDashboardResponseData interface.
 */
export function instanceOfApiDashboardResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiDashboardResponseDataFromJSON(json: any): ApiDashboardResponseData {
    return ApiDashboardResponseDataFromJSONTyped(json, false);
}

export function ApiDashboardResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDashboardResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function ApiDashboardResponseDataToJSON(value?: ApiDashboardResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'result': value.result,
    };
}

