/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiDashboardResponseData } from './ApiDashboardResponseData';
import {
    ApiDashboardResponseDataFromJSON,
    ApiDashboardResponseDataFromJSONTyped,
    ApiDashboardResponseDataToJSON,
} from './ApiDashboardResponseData';

/**
 * 
 * @export
 * @interface ApiDashboardResponse
 */
export interface ApiDashboardResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiDashboardResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiDashboardResponse
     */
    type?: string;
    /**
     * 
     * @type {ApiDashboardResponseData}
     * @memberof ApiDashboardResponse
     */
    data?: ApiDashboardResponseData;
}

/**
 * Check if a given object implements the ApiDashboardResponse interface.
 */
export function instanceOfApiDashboardResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiDashboardResponseFromJSON(json: any): ApiDashboardResponse {
    return ApiDashboardResponseFromJSONTyped(json, false);
}

export function ApiDashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDashboardResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'data': !exists(json, 'data') ? undefined : ApiDashboardResponseDataFromJSON(json['data']),
    };
}

export function ApiDashboardResponseToJSON(value?: ApiDashboardResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'type': value.type,
        'data': ApiDashboardResponseDataToJSON(value.data),
    };
}

