/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLogoutResponse
 */
export interface ApiLogoutResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiLogoutResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiLogoutResponse
     */
    type?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiLogoutResponse
     */
    data?: object;
}

/**
 * Check if a given object implements the ApiLogoutResponse interface.
 */
export function instanceOfApiLogoutResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiLogoutResponseFromJSON(json: any): ApiLogoutResponse {
    return ApiLogoutResponseFromJSONTyped(json, false);
}

export function ApiLogoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLogoutResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ApiLogoutResponseToJSON(value?: ApiLogoutResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'type': value.type,
        'data': value.data,
    };
}

