/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentLevelItem
 */
export interface ContentLevelItem {
    /**
     * 
     * @type {string}
     * @memberof ContentLevelItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContentLevelItem
     */
    contentlevelname: string;
    /**
     * 
     * @type {number}
     * @memberof ContentLevelItem
     */
    contentlevel: number;
}

/**
 * Check if a given object implements the ContentLevelItem interface.
 */
export function instanceOfContentLevelItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "contentlevelname" in value;
    isInstance = isInstance && "contentlevel" in value;

    return isInstance;
}

export function ContentLevelItemFromJSON(json: any): ContentLevelItem {
    return ContentLevelItemFromJSONTyped(json, false);
}

export function ContentLevelItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentLevelItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contentlevelname': json['contentlevelname'],
        'contentlevel': json['contentlevel'],
    };
}

export function ContentLevelItemToJSON(value?: ContentLevelItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'contentlevelname': value.contentlevelname,
        'contentlevel': value.contentlevel,
    };
}

