/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GalleryUploadDataCredentials
 */
export interface GalleryUploadDataCredentials {
    /**
     * 
     * @type {string}
     * @memberof GalleryUploadDataCredentials
     */
    user_id: string;
    /**
     * 
     * @type {number}
     * @memberof GalleryUploadDataCredentials
     */
    userContentLevel: number;
}

/**
 * Check if a given object implements the GalleryUploadDataCredentials interface.
 */
export function instanceOfGalleryUploadDataCredentials(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user_id" in value;
    isInstance = isInstance && "userContentLevel" in value;

    return isInstance;
}

export function GalleryUploadDataCredentialsFromJSON(json: any): GalleryUploadDataCredentials {
    return GalleryUploadDataCredentialsFromJSONTyped(json, false);
}

export function GalleryUploadDataCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleryUploadDataCredentials {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'userContentLevel': json['userContentLevel'],
    };
}

export function GalleryUploadDataCredentialsToJSON(value?: GalleryUploadDataCredentials | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.user_id,
        'userContentLevel': value.userContentLevel,
    };
}

