/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GalleryUploadDataResponseData } from './GalleryUploadDataResponseData';
import {
    GalleryUploadDataResponseDataFromJSON,
    GalleryUploadDataResponseDataFromJSONTyped,
    GalleryUploadDataResponseDataToJSON,
} from './GalleryUploadDataResponseData';

/**
 * 
 * @export
 * @interface GalleryUploadDataResponse
 */
export interface GalleryUploadDataResponse {
    /**
     * 
     * @type {number}
     * @memberof GalleryUploadDataResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof GalleryUploadDataResponse
     */
    type?: string;
    /**
     * 
     * @type {GalleryUploadDataResponseData}
     * @memberof GalleryUploadDataResponse
     */
    data?: GalleryUploadDataResponseData;
}

/**
 * Check if a given object implements the GalleryUploadDataResponse interface.
 */
export function instanceOfGalleryUploadDataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GalleryUploadDataResponseFromJSON(json: any): GalleryUploadDataResponse {
    return GalleryUploadDataResponseFromJSONTyped(json, false);
}

export function GalleryUploadDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleryUploadDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'data': !exists(json, 'data') ? undefined : GalleryUploadDataResponseDataFromJSON(json['data']),
    };
}

export function GalleryUploadDataResponseToJSON(value?: GalleryUploadDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'type': value.type,
        'data': GalleryUploadDataResponseDataToJSON(value.data),
    };
}

