/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GalleryRequestCredentials
 */
export interface GalleryRequestCredentials {
    /**
     * 
     * @type {string}
     * @memberof GalleryRequestCredentials
     */
    user_id: string;
    /**
     * 
     * @type {number}
     * @memberof GalleryRequestCredentials
     */
    userContentLevel: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GalleryRequestCredentials
     */
    imageKeywords: Array<string>;
}

/**
 * Check if a given object implements the GalleryRequestCredentials interface.
 */
export function instanceOfGalleryRequestCredentials(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user_id" in value;
    isInstance = isInstance && "userContentLevel" in value;
    isInstance = isInstance && "imageKeywords" in value;

    return isInstance;
}

export function GalleryRequestCredentialsFromJSON(json: any): GalleryRequestCredentials {
    return GalleryRequestCredentialsFromJSONTyped(json, false);
}

export function GalleryRequestCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleryRequestCredentials {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'userContentLevel': json['userContentLevel'],
        'imageKeywords': json['imageKeywords'],
    };
}

export function GalleryRequestCredentialsToJSON(value?: GalleryRequestCredentials | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.user_id,
        'userContentLevel': value.userContentLevel,
        'imageKeywords': value.imageKeywords,
    };
}

