/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GalleryImage
 */
export interface GalleryImage {
    /**
     * 
     * @type {number}
     * @memberof GalleryImage
     */
    galleryId: number;
    /**
     * 
     * @type {number}
     * @memberof GalleryImage
     */
    contentLevel_id: number;
    /**
     * 
     * @type {string}
     * @memberof GalleryImage
     */
    file: string;
    /**
     * 
     * @type {string}
     * @memberof GalleryImage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GalleryImage
     */
    path: string;
}

/**
 * Check if a given object implements the GalleryImage interface.
 */
export function instanceOfGalleryImage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "galleryId" in value;
    isInstance = isInstance && "contentLevel_id" in value;
    isInstance = isInstance && "file" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "path" in value;

    return isInstance;
}

export function GalleryImageFromJSON(json: any): GalleryImage {
    return GalleryImageFromJSONTyped(json, false);
}

export function GalleryImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleryImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'galleryId': json['galleryId'],
        'contentLevel_id': json['contentLevel_id'],
        'file': json['file'],
        'id': json['id'],
        'path': json['path'],
    };
}

export function GalleryImageToJSON(value?: GalleryImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'galleryId': value.galleryId,
        'contentLevel_id': value.contentLevel_id,
        'file': value.file,
        'id': value.id,
        'path': value.path,
    };
}

