/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentLevelItem } from './ContentLevelItem';
import {
    ContentLevelItemFromJSON,
    ContentLevelItemFromJSONTyped,
    ContentLevelItemToJSON,
} from './ContentLevelItem';

/**
 * 
 * @export
 * @interface SettingsPageContentResponse
 */
export interface SettingsPageContentResponse {
    /**
     * 
     * @type {number}
     * @memberof SettingsPageContentResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof SettingsPageContentResponse
     */
    type?: string;
    /**
     * 
     * @type {Array<ContentLevelItem>}
     * @memberof SettingsPageContentResponse
     */
    data?: Array<ContentLevelItem>;
}

/**
 * Check if a given object implements the SettingsPageContentResponse interface.
 */
export function instanceOfSettingsPageContentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SettingsPageContentResponseFromJSON(json: any): SettingsPageContentResponse {
    return SettingsPageContentResponseFromJSONTyped(json, false);
}

export function SettingsPageContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsPageContentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ContentLevelItemFromJSON)),
    };
}

export function SettingsPageContentResponseToJSON(value?: SettingsPageContentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'type': value.type,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ContentLevelItemToJSON)),
    };
}

