/* tslint:disable */
/* eslint-disable */
/**
 * MKSERVERMASTER API (frontend)
 * Internal API for MK-Servermaster Board.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusPing200Response
 */
export interface StatusPing200Response {
    /**
     * 
     * @type {string}
     * @memberof StatusPing200Response
     */
    msg?: string;
}

/**
 * Check if a given object implements the StatusPing200Response interface.
 */
export function instanceOfStatusPing200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StatusPing200ResponseFromJSON(json: any): StatusPing200Response {
    return StatusPing200ResponseFromJSONTyped(json, false);
}

export function StatusPing200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPing200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function StatusPing200ResponseToJSON(value?: StatusPing200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
    };
}

